version: '3.1'
services:
  db:
    container_name: "todo-db"
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todoDB

    ports:
      - "3306:3306"