version: '3.1'
services:
  db:
    container_name: "todo-db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3301:3306"