basePath: /todos
definitions:
  model.Todo:
    properties:
      complete:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a API for Todos
  title: Todo API
  version: "1.0"
paths:
  /todos:
    get:
      consumes:
      - application/json
      description: Get details of all Todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Get details of all Todos
      tags:
      - Todos
    post:
      consumes:
      - application/json
      description: Create a new Todos
      parameters:
      - description: name for new Todo
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Create a new Todo
      tags:
      - Todos
  /todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Todo by ID
      parameters:
      - description: id for delete todo
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Delete Todo
      tags:
      - Todos
    get:
      consumes:
      - application/json
      description: Get details of Todo by ID
      parameters:
      - description: id for get todo
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Get details of Todos
      tags:
      - Todos
    put:
      consumes:
      - application/json
      description: Update Todo by ID
      parameters:
      - description: id for update todo
        in: path
        name: id
        required: true
        type: integer
      - in: query
        name: complete
        type: boolean
      - in: query
        name: id
        type: integer
      - in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      summary: Update Todo
      tags:
      - Todos
swagger: "2.0"
